In [2]:
import os
import ast
import pandas as pd
import json
import numpy as np

In [3]:
pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_columns", None)

In [4]:
root_dir = "/app/data/rdb_reformulate"

In [5]:
meta_path = os.path.join(root_dir, "product", "plan", "meta.csv")

In [9]:
management_info_df = pd.read_csv(meta_path)

In [10]:
path = os.path.join(root_dir, "product", "meta.csv")
plan_meta_df = pd.read_csv(path)

In [11]:
management_info_df = pd.merge(
    management_info_df, 
    plan_meta_df, 
    on='pmProductId', 
    how='left',
    suffixes=('', '_entire')
)

In [13]:
columns_to_drop = ['approvalinfo', 'versioninfo', 'type']

In [15]:
management_info_df = management_info_df.drop(columns=columns_to_drop)

In [16]:
management_info_df.head(3)

,pmProductId,classifiedgroup,generation,lineup,marketingkeyword,productdescription,productid,productnameinenglish,productoperationperiod,productrequirednotice,productsubscriptioncondition,productsubscriptionmethod,statusofoperation,productoperationperiodFrom,productoperationperiodTo,billingmethod,monthlypricewithoutvat,monthlypricewithselectableinstallment,monthlyprice,productName,legacyProductId
0,PA00000001,상품 > 기본요금제 > 휴대폰 요금제,"['LTE', '5G']",다이렉트플랜,"['유심개통', '쓰던폰', 'USIM개통', '비대면', '자급제', '온라인', '데이터100GB 이하', 'T다샵', '다이렉트플랜', '티다이렉트샵', '티다샵', 'wavve할인혜택', '온라인전용요금제', 'T다이렉트전용요금제']",월 15GB 데이터를 제공하는 SK텔레콤 공식 온라인 채널인 T다이렉트샵에서만 가입 가능한 온라인 전용 무약정 요금제,PA00000001,Direct5G 38,2021.01.14~9999.12.31,NaN,T다이렉트샵(SK텔레콤 공식온라인채널)을 통하여 신규/기변한 고객 가입 가능,"고객센터, 대리점, T월드 가입 가능",False,2021-01-14,2262-04-11,후불,34546,38000,38000,다이렉트5G 38,NA00007164
1,PA00000002,상품 > 기본요금제 > 휴대폰 요금제,"['LTE', '5G']",LTE 다이렉트플랜,"['자급제', '비대면', '온라인', '티다샵', '티다이렉트샵', '유심개통', 'USIM개통', '쓰던폰', '심야데이터할인', 'T다이렉트전용요금제', '온라인전용요금제', '다이렉트플랜', 'T다샵']",월 1.8GB 데이터를 제공하는 SK텔레콤 공식 온라인 채널인 T다이렉트샵에서만 가입 가능한 온라인 전용 무약정 요금제,PA00000002,DirectLTE 22,2021.01.14~9999.12.31,NaN,T다이렉트샵(SK텔레콤 공식온라인채널)을 통하여 신규/기변한 고객 가입 가능,"고객센터, 대리점, T월드 가입 가능",False,2021-01-14,2262-04-11,후불,20000,22000,22000,다이렉트LTE 22,NA00007166
2,PA00000003,상품 > 기본요금제 > 휴대폰 요금제,"['LTE', '5G']",LTE 다이렉트플랜,"['쓰던폰', '자급제', '비대면', '온라인', '티다이렉트샵', '유심개통', 'USIM개통', '심야데이터할인', 'T다이렉트전용요금제', '온라인전용요금제', '다이렉트플랜', 'T다샵', '티다샵']",월 5GB 데이터를 제공하는 SK텔레콤 공식 온라인 채널인 T다이렉트샵에서만 가입 가능한 온라인 전용 무약정 요금제,PA00000003,DirectLTE 35,2021.01.14~9999.12.31,NaN,T다이렉트샵(SK텔레콤 공식온라인채널)을 통하여 신규/기변한 고객 가입 가능,"고객센터, 대리점, T월드 가입 가능",False,2021-01-14,2262-04-11,후불,31819,35000,35000,다이렉트LTE 35,NA00007167

In [18]:
custom_info = pd.read_csv(os.path.join(root_dir, "customerinfo", "meta.csv"))

In [20]:
custom_info.loc[custom_info.pmProductId=="PA00000068"]

,pmProductId,welfarediscounttypeavailability,agerule,businesscustomersubtyperule,customertyperule,individualcustomersubtyperule,organizationcustomersubtyperule
67,PA00000068,{},"[0, 999]","['SKBroadband㈜', 'SKTelecom㈜']",['개인'],"['공무원', '일반']",{}